### ISSUE TITLE
RDMA传输文件失败

### ISSUE THREAD

**Issue by hellofinch** [hellofinch/rdma-grpc#1]

**Comment by Tuvie** [comment]
我对grpc的代码不熟悉。你需要给一些具体的描述

**Comment by hellofinch** [comment]
感谢您抽时间回答我的问题。

RDMA相关的代码主要添加在[这里](https://github.com/hellofinch/rdma-grpc/tree/main/src/core/lib/iomgr)，一共包含三类文件，client连接相关的代码，server用来处理连接的相关代码以及RDMA通信所依赖的方法和相关数据结构。
ib_client_posix.cc：主要实现了client对于RDMA通信的连接建立过程，以及对于client端的RDMA_CM_EVENT的监听和响应。
ib_server_posix.cc：主要实现了server对于RDMA通信的建立过程，以及对于server端的RDMA_CM_EVENT的监听和响应。
server和client的数据处理部分利用closure，在(这里)[https://github.com/hellofinch/rdma-grpc/blob/main/src/core/ext/transport/chttp2/transport/chttp2_transport.cc]进行网络层数据的处理。
rmda_cm.cc：主要实现了grpc endpoint所需要的通信接口函数。其中包含了ibv_get_cq_event()，rdma_post_send()、rdma_post_recv()等RDMA通信的操作。以及grpc endpoint的初始化。
rdma_memory_management.cc：主要用来管理RDMA通信来的内存如何管理和对接到gRPC中
rdma_utils_posix.cc和rdma_utils_posix.h：包含了RDMA通信相关的上下文信息的结构体。

在执行过程中，server端会在(这里)[https://github.com/hellofinch/rdma-grpc/blob/main/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2531]报错，出现segmentation fault的问题，然后client端abort退出。

gRPC的整个结构比较复杂，上述的内容我把我添加的部分描述出来了，一些小的修改我没有指出，基本上都是在之前TCP的基础上修改为RDMA的函数。

如果您方便的话，我们是否可以线上会议一下直接沟通？有一些问题我不知道应该用如何组织描述。

谢谢。

**Comment by Tuvie** [comment]
我建议还是从segfault的地方触发，debug定位下问题一步步追查吧。按照你的描述，可以看看stream场景中有啥不一样的？

**Comment by hellofinch** [comment]
感谢您抽时间看了我的描述并提出了建议。

我之前试着用gdb去调试，但是服务器端和客户端两个程序，在服务器端打上断点，但是开始debug之后客户端直接就运行然后停了一会就退出来了，服务器端还是可以正常debug，一步一步执行的。我不太熟练这种网络程序的debug。

我这两天仔细想了想流式和非流式的问题，主要的差别我认为是对内存的持续读写。在非流式里边客户端就把数据放那就结束了，但是流式的话，需要客户端和服务器协同管理一块内存。

我对RDMA的了解和使用不是特别明白，您方便的话，可以与您语音沟通一下？文字的交流可能有些欠缺。

谢谢

**Comment by hellofinch** [comment]
@Tuvie 您好，
RDMA使用中，函数参数中经常出现context这个词，这个东西到底是个什么？我应该设置什么在这里？这个地方我一直没有能理解。方便的话您能解释一下吗？

**Comment by Tuvie** [comment]
多数情况下用不到可以不管。
